### ISSUE TITLE
Number of threads

### ISSUE THREAD

**Issue by lcebaman** [yvonnezou/Hybrid_MPI-OpenMP#1]
*The number of threads (nthreads) should be provided at runtime instead of hard-coded in the cfd.c
*Then, your cfd.pbs should provide the number of threads; on a Cray system like ARCHER is indicated with -d: e.g:

export OMP_NUM_THREADS= 2
aprun -n 4 -d 2./cfd

**Comment by yvonnezou** [comment]
Solved in the multiple directory
